import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — How to Talk Corporate',
};

export default function TermsPage() {
  return (
    <article className="prose prose-sm max-w-none">
      <h1 className="font-serif text-3xl font-black">Terms of Service</h1>
      <p className="text-ink-3">Last updated: May 9, 2026</p>

      <h2>1. Acceptance</h2>
      <p>
        By using How to Talk Corporate (&quot;the Service&quot;), you agree to these terms. If you
        do not agree, do not use the Service.
      </p>

      <h2>2. Service description</h2>
      <p>
        How to Talk Corporate is a free, zero-login web application and browser extension that
        rewrites workplace messages with the appropriate tone. The Service is provided &quot;as
        is&quot; without warranty of any kind.
      </p>

      <h2>3. Rate limits and fair use</h2>
      <p>
        The Service is offered at no cost with a rate limit of 10 rewrites per 24-hour rolling
        window per device. This limit is enforced by a hashed fingerprint; circumvention (e.g. by
        rotating identifiers to bypass the limit) is prohibited and may result in a permanent IP
        ban. How to Talk Corporate reserves the right to adjust rate limits at any time without
        notice.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose</li>
        <li>Attempt to reverse-engineer the agent pipeline or the rewrite logic</li>
        <li>Submit malicious prompts designed to inject instructions into the LLM pipeline</li>
        <li>Use automated tools (bots, scrapers) to exceed the rate limit</li>
        <li>Impersonate another person or entity</li>
      </ul>

      <h2>5. Disclaimer of warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; HOW TO TALK
        CORPORATE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY, OR
        SUITABILITY OF REWRITTEN CONTENT. REWRITTEN MESSAGES ARE GENERATED BY AN AI MODEL AND SHOULD
        BE REVIEWED BEFORE SENDING. HOW TO TALK CORPORATE IS NOT RESPONSIBLE FOR ANY
        MISCOMMUNICATION, OFFENCE, OR OTHER HARM ARISING FROM THE USE OF REWRITTEN CONTENT.
      </p>

      <h2>6. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, HOW TO TALK CORPORATE SHALL NOT BE LIABLE FOR ANY
        INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF
        THE SERVICE.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        Your original message and the rewritten output remain your property. How to Talk Corporate
        does not claim ownership of any content processed through the Service.
      </p>

      <h2>8. Changes to these terms</h2>
      <p>
        These terms may be updated from time to time. Continued use of the Service after changes
        constitutes acceptance of the updated terms. The &quot;Last updated&quot; date at the top of
        this page reflects the most recent revision.
      </p>

      <h2>9. Governing law</h2>
      <p>
        These terms are governed by the laws of India. Any disputes shall be resolved in the courts
        of Bangalore, India.
      </p>

      <h2>10. Contact</h2>
      <p>
        For questions about these terms, open an issue at{' '}
        <a
          href="https://github.com/itsmuskanagarwal/professional-message-writer"
          className="underline"
        >
          github.com/itsmuskanagarwal/professional-message-writer
        </a>
        .
      </p>
    </article>
  );
}
